/**
 * Document Generation Service
 * Generates PDFs and documents for compliance, invoices, and confirmations
 */

class DocumentGenerationService {
  constructor(db) {
    this.db = db;
  }

  /**
   * Generate USDOT application PDF
   */
  async generateUSDOTApplicationPDF(applicationId) {
    // Get application data
    const application = await this.getApplicationData(applicationId);
    
    // Generate HTML template
    const html = this.generateUSDOTHTML(application);
    
    // Convert to PDF (using browser print or PDF library)
    return {
      success: true,
      fileName: `USDOT_Application_${application.id}.pdf`,
      html, // Can be converted to PDF in browser or with library
      downloadUrl: `/api/documents/download/${applicationId}`
    };
  }

  /**
   * Generate invoice PDF
   */
  async generateInvoicePDF(invoiceId) {
    const invoice = await this.getInvoiceData(invoiceId);
    const html = this.generateInvoiceHTML(invoice);
    
    return {
      success: true,
      fileName: `Invoice_${invoice.id}.pdf`,
      html,
      downloadUrl: `/api/documents/invoice/${invoiceId}`
    };
  }

  /**
   * Generate compliance certificate
   */
  async generateComplianceCertificate(companyId, serviceName) {
    const company = await this.getCompanyData(companyId);
    const html = this.generateCertificateHTML(company, serviceName);
    
    return {
      success: true,
      fileName: `${serviceName}_Certificate_${company.id}.pdf`,
      html,
      downloadUrl: `/api/documents/certificate/${companyId}/${serviceName}`
    };
  }

  /**
   * Generate USDOT application HTML
   */
  generateUSDOTHTML(application) {
    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>USDOT Application - ${application.legal_business_name}</title>
        <style>
          body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; }
          h1 { color: #1e40af; border-bottom: 3px solid #3b82f6; padding-bottom: 10px; }
          h2 { color: #374151; margin-top: 30px; }
          .field { margin: 15px 0; }
          .label { font-weight: bold; color: #4b5563; }
          .value { margin-left: 10px; }
          table { width: 100%; border-collapse: collapse; margin: 20px 0; }
          th, td { padding: 10px; text-align: left; border: 1px solid #d1d5db; }
          th { background: #f3f4f6; font-weight: bold; }
          .footer { margin-top: 50px; padding-top: 20px; border-top: 2px solid #e5e7eb; color: #6b7280; font-size: 12px; }
        </style>
      </head>
      <body>
        <h1>USDOT Number Application</h1>
        
        <div class="field">
          <span class="label">Application ID:</span>
          <span class="value">${application.id}</span>
        </div>
        
        <div class="field">
          <span class="label">Application Date:</span>
          <span class="value">${new Date(application.created_at).toLocaleDateString()}</span>
        </div>
        
        <h2>Company Information</h2>
        <table>
          <tr><th>Legal Business Name</th><td>${application.legal_business_name}</td></tr>
          ${application.dba_name ? `<tr><th>DBA Name</th><td>${application.dba_name}</td></tr>` : ''}
          <tr><th>Business Type</th><td>${application.business_type}</td></tr>
          <tr><th>EIN</th><td>${application.ein}</td></tr>
        </table>
        
        <h2>Principal Address</h2>
        <p>
          ${application.principal_address_street}<br>
          ${application.principal_address_city}, ${application.principal_address_state} ${application.principal_address_zip}
        </p>
        
        <h2>Fleet Information</h2>
        <table>
          <tr><th>Number of Vehicles</th><td>${application.number_of_vehicles}</td></tr>
          <tr><th>Number of Drivers</th><td>${application.number_of_drivers}</td></tr>
          <tr><th>Vehicle Types</th><td>${application.vehicle_types_used || 'Not specified'}</td></tr>
        </table>
        
        <h2>Operation Details</h2>
        <table>
          <tr><th>Operation Type</th><td>${application.transportation_operation_type}</td></tr>
          <tr><th>Interstate/Intrastate</th><td>${application.interstate_intrastate}</td></tr>
          <tr><th>Cargo Types</th><td>${application.cargo_types_transported}</td></tr>
          <tr><th>Hazmat Placarding</th><td>${application.hazmat_placard_required}</td></tr>
        </table>
        
        <div class="footer">
          <p>This document was generated by Rapid CRM on ${new Date().toLocaleDateString()}.</p>
          <p>For questions or assistance, contact: support@rapidcrm.com</p>
        </div>
      </body>
      </html>
    `;
  }

  /**
   * Generate invoice HTML
   */
  generateInvoiceHTML(invoice) {
    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Invoice ${invoice.id}</title>
        <style>
          body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; }
          h1 { color: #1e40af; }
          .header { display: flex; justify-content: space-between; margin-bottom: 40px; }
          .company-info { text-align: right; }
          table { width: 100%; border-collapse: collapse; margin: 20px 0; }
          th, td { padding: 12px; text-align: left; border-bottom: 1px solid #d1d5db; }
          th { background: #f3f4f6; font-weight: bold; }
          .total { font-size: 18px; font-weight: bold; text-align: right; margin-top: 20px; }
          .footer { margin-top: 50px; padding-top: 20px; border-top: 2px solid #e5e7eb; color: #6b7280; font-size: 12px; text-align: center; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1>INVOICE</h1>
            <p><strong>Invoice #:</strong> ${invoice.id}</p>
            <p><strong>Date:</strong> ${new Date(invoice.created_at).toLocaleDateString()}</p>
            <p><strong>Due Date:</strong> ${new Date(invoice.due_date || invoice.created_at).toLocaleDateString()}</p>
          </div>
          <div class="company-info">
            <strong>Rapid CRM</strong><br>
            Transportation Compliance Services<br>
            support@rapidcrm.com
          </div>
        </div>
        
        <div style="margin-bottom: 30px;">
          <strong>Bill To:</strong><br>
          ${invoice.client_name}<br>
          ${invoice.client_email}
        </div>
        
        <table>
          <thead>
            <tr>
              <th>Description</th>
              <th>Quantity</th>
              <th>Price</th>
              <th>Amount</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>${invoice.description || 'Transportation Compliance Services'}</td>
              <td>1</td>
              <td>$${invoice.amount}</td>
              <td>$${invoice.amount}</td>
            </tr>
          </tbody>
        </table>
        
        <div class="total">
          <p>TOTAL: $${invoice.amount}</p>
          <p style="color: ${invoice.status === 'paid' ? '#059669' : '#dc2626'}; font-size: 14px;">
            Status: ${invoice.status.toUpperCase()}
          </p>
        </div>
        
        <div class="footer">
          <p>Thank you for your business!</p>
          <p>Questions? Contact us at support@rapidcrm.com</p>
        </div>
      </body>
      </html>
    `;
  }

  /**
   * Generate compliance certificate HTML
   */
  generateCertificateHTML(company, serviceName) {
    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Compliance Certificate</title>
        <style>
          body { font-family: Georgia, serif; max-width: 800px; margin: 60px auto; padding: 40px; border: 10px solid #3b82f6; }
          h1 { text-align: center; color: #1e40af; font-size: 36px; margin-bottom: 10px; }
          h2 { text-align: center; color: #6b7280; font-size: 20px; margin-top: 0; }
          .certificate-body { text-align: center; margin: 60px 0; }
          .company-name { font-size: 28px; font-weight: bold; color: #1f2937; margin: 30px 0; }
          .service-name { font-size: 20px; color: #4b5563; margin: 20px 0; }
          .date { margin-top: 60px; color: #6b7280; }
          .signature { margin-top: 80px; border-top: 2px solid #1f2937; padding-top: 10px; max-width: 300px; margin-left: auto; margin-right: auto; }
        </style>
      </head>
      <body>
        <h1>CERTIFICATE OF COMPLIANCE</h1>
        <h2>Transportation Compliance Services</h2>
        
        <div class="certificate-body">
          <p>This is to certify that</p>
          
          <div class="company-name">${company.legal_business_name || company.legalBusinessName}</div>
          
          <p>has completed the requirements for</p>
          
          <div class="service-name">${serviceName}</div>
          
          <p>and is in good standing with applicable federal and state regulations.</p>
          
          <div class="date">
            <p>Issue Date: ${new Date().toLocaleDateString()}</p>
            ${company.usdot_number ? `<p>USDOT Number: ${company.usdot_number}</p>` : ''}
          </div>
          
          <div class="signature">
            <p><strong>Rapid CRM</strong></p>
            <p>Transportation Compliance Agency</p>
          </div>
        </div>
      </body>
      </html>
    `;
  }

  /**
   * Get application data
   */
  async getApplicationData(applicationId) {
    return new Promise((resolve, reject) => {
      this.db.get('SELECT * FROM usdot_applications WHERE id = ?', [applicationId], (err, row) => {
        if (err) return reject(err);
        if (!row) return reject(new Error('Application not found'));
        resolve(row);
      });
    });
  }

  /**
   * Get invoice data
   */
  async getInvoiceData(invoiceId) {
    return new Promise((resolve, reject) => {
      this.db.get('SELECT * FROM invoices WHERE id = ?', [invoiceId], (err, row) => {
        if (err) return reject(err);
        if (!row) return reject(new Error('Invoice not found'));
        resolve(row);
      });
    });
  }

  /**
   * Get company data
   */
  async getCompanyData(companyId) {
    return new Promise((resolve, reject) => {
      this.db.get('SELECT * FROM companies WHERE id = ?', [companyId], (err, row) => {
        if (err) return reject(err);
        if (!row) return reject(new Error('Company not found'));
        resolve(row);
      });
    });
  }
}

module.exports = DocumentGenerationService;










